### ISSUE TITLE
Please fork the repo

### ISSUE THREAD

**Issue by drasko** [AleksandarSavic95/iot-rpi#1]
Hi @AleksandarSavic95 instead of copying entirely Mainflux code, can you please try some of the following approaches:
1. Keep only your changes in your repo and import Mainflux Go packages as usual (in your `vendor` for example)
2. If this is compliacted, then plese **fork** Mainflux repository and add your changes

The way it is done today is confusing - it gives an impression that you re the author of the code and that 21 contributor worked on your BS thesis :)

**Comment by AleksandarSavic95** [comment]
I am so sorry for making this mistake. It was completely unintentional. In my thesis, I clearly stated that Mainflux was an existing, open-source project that I (only) **used**, and I haven't written that I made it myself (except the ~20 lines of code I added for the messaging part).
I will delete this repo, since it was just a temporary solution to the problem of sending messages through Dashflux.
Since the changes aren't big nor "smart", I don't think that there is a need for forking and committing the changes. But, if You think I should do it, please tell me.

I apologize once again.
I am waiting for Your response and after that I will delete the repo.

Kind regards,
Aleksandar

**Comment by drasko** [comment]
@AleksandarSavic95 np, if you are going to remove repo - that's good.

There is no need to apologize, we understand and appreciate your work. Just that Apache-2.0 license under which Mainflux is published must be respected.

**Comment by AleksandarSavic95** [comment]
Ok, thanks :) 
Deleting the repo now..
